application:
  properties:
    title: Hello! World!

spring:
  datasource:
    url: jdbc:h2:file:~/todo_app/todos
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
